linters:
  enable:
    - bodyclose
    - containedctx
    - contextcheck
    - deadcode
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - exhaustive
    - forcetypeassert
    - gocognit
    - goconst
    - gocritic
    - godox
    - goerr113
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - tenv
    - thelper
    - typecheck
    - unconvert
    - unused
    - varcheck
