name: prepare-img-tag
author: snapADDY GmbH
description: Prepare a tag for Docker images and decide if they should be published
inputs:
  commitMessage:
    description: Git commit message
    required: true
    default: ${{ github.event.head_commit.message }}
outputs:
  tag-name:
    description: Docker image tag
  publish:
    description: Decides if images should be published
  env-name:
    description: Name of the environment (first part of the image tag)
  env-override:
    description: Env name override of [img:override] message flag
  has-img-flag:
    description: Commit message contains a [img] message flag
runs:
  using: "docker"
  image: "docker://ghcr.io/snapaddy/actions-prepare-img-tag:1.4.0"
