name: (FAILS) Code security check with bandit
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Run Bandit
      uses: snapADDY/actions/bandit-github@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        path: "./bandit-github/"
        level: low
        confidence: low
