name: Code security check with bandit
on:
  pull_request
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 5

    - name: Obtain message from last commit
      run: |
        echo "commitmsg=$(echo $(git log --format=%B -n 1 ${{ github.event.after }}))" >> $GITHUB_ENV
    # - name: Post Report
    #   id: post_report
    #   if: contains(env.commitmsg, 'check_security')
    #   run: export BANDIT_COMMENT_ON_PULL_REQUEST=True


    - name: Run Bandit
      id: run_bandit
      uses: snapADDY/actions/bandit-github@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        path: "./bandit-github/"
        level: low
        confidence: low
