name: Lint and Test
on:
  pull_request:
  push:

jobs:
  go-lint-test:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-go@v3
          with:
            go-version: '1.18'

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.50.1

        - run: make test
